### ISSUE TITLE
Table Name Case

### ISSUE THREAD

**Issue by Notanotherdotcom** [apeisa/ProcessRedirects#10]
Hi Antti

Ran into this issue on two different servers (same site, staging server and live server but very different server setups).

Basically, on my WAMP localhost, if I install ProcessRedirects, the table is lowercase in the DB (pretty common on WAMP I think) but your code intends for it to be created with the same case as the class name, so capital P and R. WAMP doesn't seem to care much what case your table name is and will happily work with either so it doesn't error even though the name has been lowercased.

When you migrate the site to your live, linux server, it definitely is case-sensitive at that point and throws an error that you might not immediately notice unless you're being thorough and testing those redirects still work (which of course you should be testing when launching a site :)).

I'm not sure what the solution is really though as it would be a bit of work to force it to alter the table name to be lowercase throughout in a newer version.

**Comment by teppokoivula** [comment]
Hey Pete — this issue should now be fixed in module version 2.0.0, which converts PascalCase database table to snake_case. Five years later, so I'm guessing (and hoping) you haven't been holding your breath; I'll close this issue now :)
