### ISSUE TITLE
Support Cyrilic Alphabet

### ISSUE THREAD

**Issue by TomasKostadinov** [apeisa/ProcessRedirects#11]
Links with cyrillic symbols always (eg. /bg/естетична-стоматология.html)  return 404. This is a problem for moving Bulgarian/Russian/... sites to ProcessWire with this plugin

**Comment by apeisa** [comment]
That is probably due PW not supporting any other characters in urls than a-z, dash, underscore and numbers. I think such redirects should be done earlier (like in htaccess) than how this module works. Might be worth trying how to do it with Jumplinks module, which is much newer and more feature rich - it might solve your issue.

**Comment by TomasKostadinov** [comment]
Found a solution: Convert them so they look like this: /bg/%D0%BD%D
%D0%BD%D0%BE%D0%B2%D0%B8%D0%BD%D0%B8.html. This could be done maybe automatically
