### ISSUE TITLE
Failed to add redirect because path is similar

### ISSUE THREAD

**Issue by david-schopf** [apeisa/ProcessRedirects#21]
Hi, I have the following setup:
ProcessWire 3.0.164
PHP 7.2
ProcessRedirects 2.0.1

When I want to add a redirect for "/content/nach-der-geburt" to "/kurse/nach-der-geburt", I get this error message:
The Redirect From URL already exists as a page path. Redirect not added.

The path "/content" does not exist in my installation. But obviously, the sub-page path "nach-der-geburt" is matched.
Another example that is not working: "/content/agbs" => "/agbs"

How can I add the redirect for "/content" URLs?

**Comment by teppokoivula** [comment]
Looks like a bug — the module uses $pages->getByPath() to check if the path exists, and the docblock for this method states that...

```
	 * 3. Partial paths may also match, so long as the partial path is completely unique in the site.
	 *    If you don't want that behavior, double check the path of the returned page.
```

Seems like an easy fix, but needs a bit of testing. I'll get back to this ASAP.

**Comment by teppokoivula** [comment]
@david-schopf, this should be fixed in latest module version.
