### ISSUE TITLE
Lowercase table names on Windows

### ISSUE THREAD

**Issue by formmailer** [apeisa/ProcessRedirects#4]
Hi,

I installed the redirect module on my Windows computer, using XAMPP and it works fine, but the table ProcessRedirects is created with a lowercase name: processredirects. 
After moving my site to my production server, running Linux, the module stops working with the following error: Table 'processwire.ProcessRedirects' doesn't exist, which is correct since the table is referenced as {$this->className} 

Ryan had the same issue with all other tables and decided to force all tablenames to lowercase. It might be smart to do this in your module as well.

I did this on my install, using strtolower(), and it works fine. I can do a pull request, but I think it might be faster to edit the 9 occurences manually. :-)

/Jasper

**Comment by teppokoivula** [comment]
Latest version of the module changed table name to process_redirects, so this should be fixed by now 👌
