### ISSUE TITLE
Sortorder "Hits"

### ISSUE THREAD

**Issue by DV-JF** [apeisa/ProcessRedirects#7]
Hi,
when I click on "Hits" the ordering isn't correct, have a look at the screen-shot.

![2015-01-27 11_43_44-](https://cloud.githubusercontent.com/assets/3637410/5917153/0f64d380-a61a-11e4-9201-47ecf7a059fe.jpg)

Many greets

**Comment by apeisa** [comment]
Thanks for the report. It's using the pw default MarkupAdminDataTable which isn't very good at sorting. Not sure if there is any easy fix for this?

**Comment by teppokoivula** [comment]
Sorting seems to work fine now — closing this issue.
